# Generated by Django 3.2.25 on 2024-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_sick',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Paciente possui algum distúrbio de tireoide'),
            preserve_default=False,
        ),
    ]
