# Generated by Django 3.2.25 on 2024-10-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_patient_patient_sick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.IntegerField(choices=[(0, 'F'), (1, 'M')], verbose_name='Sexo do paciente'),
        ),
    ]
